---
AWSTemplateFormatVersion: "2010-09-09"
Description: "ECR Runbook"

Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html
  SSMDocumentECRImageScanningEnable:
    Type: "AWS::SSM::Document"
    Properties:
      Content:
        schemaVersion: "0.3"
        description: "Turn on ECR image scan"
        parameters:
          AutomationAssumeRole:
            type: "String"
            description: "(Optional) The ARN of the role that allows Automation to perform the actions on your behalf."
            default: ""
          RepositoryName:
            type: "String"
            allowedPattern: "(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*"
            description: "The name of the repository in which to update the image scanning configuration setting."
        assumeRole: "{{ AutomationAssumeRole }}"
        mainSteps:
          - description: "APIref. https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_PutImageScanningConfiguration.html"
            name: "PutImageScanningConfiguration"
            action: "aws:executeAwsApi"
            isEnd: true
            inputs:
              Service: "ecr"
              Api: "PutImageScanningConfiguration"
              repositoryName: "{{ RepositoryName }}"
              imageScanningConfiguration:
                scanOnPush: true
      DocumentFormat: "YAML"
      DocumentType: "Automation"
      Name: "ECRImageScanningEnable"

  IAMRoleAutomationServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ssm.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub ${AWS::AccountId}
              ArnLike:
                aws:SourceArn: !Sub arn:aws:ssm:*:${AWS::AccountId}:automation-execution/*
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonSSMAutomationRole
      Policies:
        - PolicyName: "AutomationServiceRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ecr:PutImageScanningConfiguration"
                Resource: "*"
      Path: "/"
      RoleName: AutomationServiceRole

  ConfigConfigRuleECRPrivateImageScanningEnabled:
    Type: "AWS::Config::ConfigRule"
    Properties:
      ConfigRuleName: "ecr-private-image-scanning-enabled"
      Description: "Checks if a private Amazon Elastic Container Registry (ECR) repository has image scanning enabled. The rule is NON_COMPLIANT if the private ECR repository's scan frequency is not on scan on push or continuous scan."
      Source:
        Owner: "AWS"
        SourceIdentifier: "ECR_PRIVATE_IMAGE_SCANNING_ENABLED"
      MaximumExecutionFrequency: "TwentyFour_Hours"

  ConfigRemediationConfigurationECRImageScanningEnable:
    Type: AWS::Config::RemediationConfiguration
    Properties:
      Automatic: true
      ConfigRuleName: !Ref ConfigConfigRuleECRPrivateImageScanningEnabled
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 25
          ErrorPercentage: 35
      MaximumAutomaticAttempts: 5
      RetryAttemptSeconds: 60
      TargetId: !Ref SSMDocumentECRImageScanningEnable
      TargetType: "SSM_DOCUMENT"
      TargetVersion: "1"
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values:
              - !GetAtt IAMRoleAutomationServiceRole.Arn
        RepositoryName:
          ResourceValue:
            Value: "RESOURCE_ID"
